//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALIBA_COMPANY
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AlibaRamyEntities : DbContext
    {
        public AlibaRamyEntities()
            : base("name=AlibaRamyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TB_action> TB_action { get; set; }
        public virtual DbSet<TB_actions> TB_actions { get; set; }
        public virtual DbSet<TB_amov> TB_amov { get; set; }
        public virtual DbSet<TB_branchs> TB_branchs { get; set; }
        public virtual DbSet<TB_cars> TB_cars { get; set; }
        public virtual DbSet<TB_city> TB_city { get; set; }
        public virtual DbSet<TB_cridet> TB_cridet { get; set; }
        public virtual DbSet<TB_cust> TB_cust { get; set; }
        public virtual DbSet<TB_det> TB_det { get; set; }
        public virtual DbSet<TB_det1> TB_det1 { get; set; }
        public virtual DbSet<TB_details> TB_details { get; set; }
        public virtual DbSet<TB_details1> TB_details1 { get; set; }
        public virtual DbSet<TB_emplo> TB_emplo { get; set; }
        public virtual DbSet<TB_emr> TB_emr { get; set; }
        public virtual DbSet<TB_emst> TB_emst { get; set; }
        public virtual DbSet<TB_groups> TB_groups { get; set; }
        public virtual DbSet<TB_items> TB_items { get; set; }
        public virtual DbSet<TB_list> TB_list { get; set; }
        public virtual DbSet<TB_list1> TB_list1 { get; set; }
        public virtual DbSet<TB_mov> TB_mov { get; set; }
        public virtual DbSet<TB_Note> TB_Note { get; set; }
        public virtual DbSet<TB_order> TB_order { get; set; }
        public virtual DbSet<TB_order1> TB_order1 { get; set; }
        public virtual DbSet<TB_stock> TB_stock { get; set; }
        public virtual DbSet<TB_str> TB_str { get; set; }
        public virtual DbSet<TB_str1> TB_str1 { get; set; }
        public virtual DbSet<TB_temp> TB_temp { get; set; }
        public virtual DbSet<TB_travel> TB_travel { get; set; }
        public virtual DbSet<TB_travel1> TB_travel1 { get; set; }
        public virtual DbSet<TB_type> TB_type { get; set; }
        public virtual DbSet<TB_users> TB_users { get; set; }
        public virtual DbSet<TB_ads> TB_ads { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> GetItemStored(Nullable<int> itemId)
        {
            var itemIdParameter = itemId.HasValue ?
                new ObjectParameter("ItemId", itemId) :
                new ObjectParameter("ItemId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("GetItemStored", itemIdParameter);
        }
    
        public virtual ObjectResult<SearchInventory_Result> SearchInventory(string selectedItemsName, string selectedCatg, Nullable<decimal> quantity, string selectedcompare, Nullable<System.DateTime> selectDate)
        {
            var selectedItemsNameParameter = selectedItemsName != null ?
                new ObjectParameter("selectedItemsName", selectedItemsName) :
                new ObjectParameter("selectedItemsName", typeof(string));
    
            var selectedCatgParameter = selectedCatg != null ?
                new ObjectParameter("selectedCatg", selectedCatg) :
                new ObjectParameter("selectedCatg", typeof(string));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(decimal));
    
            var selectedcompareParameter = selectedcompare != null ?
                new ObjectParameter("selectedcompare", selectedcompare) :
                new ObjectParameter("selectedcompare", typeof(string));
    
            var selectDateParameter = selectDate.HasValue ?
                new ObjectParameter("selectDate", selectDate) :
                new ObjectParameter("selectDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchInventory_Result>("SearchInventory", selectedItemsNameParameter, selectedCatgParameter, quantityParameter, selectedcompareParameter, selectDateParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<FilteredTravelRecords_Result> FilteredTravelRecords(Nullable<decimal> waselValue, Nullable<decimal> itemsValue, Nullable<decimal> unitsValue, string driverName, string cityName, string carName, string status, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var waselValueParameter = waselValue.HasValue ?
                new ObjectParameter("WaselValue", waselValue) :
                new ObjectParameter("WaselValue", typeof(decimal));
    
            var itemsValueParameter = itemsValue.HasValue ?
                new ObjectParameter("ItemsValue", itemsValue) :
                new ObjectParameter("ItemsValue", typeof(decimal));
    
            var unitsValueParameter = unitsValue.HasValue ?
                new ObjectParameter("UnitsValue", unitsValue) :
                new ObjectParameter("UnitsValue", typeof(decimal));
    
            var driverNameParameter = driverName != null ?
                new ObjectParameter("DriverName", driverName) :
                new ObjectParameter("DriverName", typeof(string));
    
            var cityNameParameter = cityName != null ?
                new ObjectParameter("CityName", cityName) :
                new ObjectParameter("CityName", typeof(string));
    
            var carNameParameter = carName != null ?
                new ObjectParameter("CarName", carName) :
                new ObjectParameter("CarName", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FilteredTravelRecords_Result>("FilteredTravelRecords", waselValueParameter, itemsValueParameter, unitsValueParameter, driverNameParameter, cityNameParameter, carNameParameter, statusParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<SP_GetCustomerExch_Result> SP_GetCustomerExch(string emplo_name, string list_name)
        {
            var emplo_nameParameter = emplo_name != null ?
                new ObjectParameter("emplo_name", emplo_name) :
                new ObjectParameter("emplo_name", typeof(string));
    
            var list_nameParameter = list_name != null ?
                new ObjectParameter("list_name", list_name) :
                new ObjectParameter("list_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetCustomerExch_Result>("SP_GetCustomerExch", emplo_nameParameter, list_nameParameter);
        }
    
        public virtual ObjectResult<close_travel_Result> close_travel(Nullable<int> tid, Nullable<int> user_id, Nullable<decimal> amount, Nullable<decimal> amount_d, Nullable<decimal> cash, Nullable<decimal> cash_d, Nullable<decimal> cridet, Nullable<decimal> cridet_d, Nullable<decimal> scash, Nullable<decimal> dcash, Nullable<decimal> recridetu, Nullable<decimal> recridetu_d, Nullable<decimal> recrideth, Nullable<decimal> recrideth_d, Nullable<decimal> dcashh, Nullable<decimal> scashh, Nullable<decimal> sfinal, Nullable<decimal> dfinal, Nullable<decimal> items, Nullable<decimal> units, Nullable<int> lists)
        {
            var tidParameter = tid.HasValue ?
                new ObjectParameter("tid", tid) :
                new ObjectParameter("tid", typeof(int));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(decimal));
    
            var amount_dParameter = amount_d.HasValue ?
                new ObjectParameter("amount_d", amount_d) :
                new ObjectParameter("amount_d", typeof(decimal));
    
            var cashParameter = cash.HasValue ?
                new ObjectParameter("cash", cash) :
                new ObjectParameter("cash", typeof(decimal));
    
            var cash_dParameter = cash_d.HasValue ?
                new ObjectParameter("cash_d", cash_d) :
                new ObjectParameter("cash_d", typeof(decimal));
    
            var cridetParameter = cridet.HasValue ?
                new ObjectParameter("cridet", cridet) :
                new ObjectParameter("cridet", typeof(decimal));
    
            var cridet_dParameter = cridet_d.HasValue ?
                new ObjectParameter("cridet_d", cridet_d) :
                new ObjectParameter("cridet_d", typeof(decimal));
    
            var scashParameter = scash.HasValue ?
                new ObjectParameter("scash", scash) :
                new ObjectParameter("scash", typeof(decimal));
    
            var dcashParameter = dcash.HasValue ?
                new ObjectParameter("dcash", dcash) :
                new ObjectParameter("dcash", typeof(decimal));
    
            var recridetuParameter = recridetu.HasValue ?
                new ObjectParameter("recridetu", recridetu) :
                new ObjectParameter("recridetu", typeof(decimal));
    
            var recridetu_dParameter = recridetu_d.HasValue ?
                new ObjectParameter("recridetu_d", recridetu_d) :
                new ObjectParameter("recridetu_d", typeof(decimal));
    
            var recridethParameter = recrideth.HasValue ?
                new ObjectParameter("recrideth", recrideth) :
                new ObjectParameter("recrideth", typeof(decimal));
    
            var recrideth_dParameter = recrideth_d.HasValue ?
                new ObjectParameter("recrideth_d", recrideth_d) :
                new ObjectParameter("recrideth_d", typeof(decimal));
    
            var dcashhParameter = dcashh.HasValue ?
                new ObjectParameter("dcashh", dcashh) :
                new ObjectParameter("dcashh", typeof(decimal));
    
            var scashhParameter = scashh.HasValue ?
                new ObjectParameter("scashh", scashh) :
                new ObjectParameter("scashh", typeof(decimal));
    
            var sfinalParameter = sfinal.HasValue ?
                new ObjectParameter("sfinal", sfinal) :
                new ObjectParameter("sfinal", typeof(decimal));
    
            var dfinalParameter = dfinal.HasValue ?
                new ObjectParameter("dfinal", dfinal) :
                new ObjectParameter("dfinal", typeof(decimal));
    
            var itemsParameter = items.HasValue ?
                new ObjectParameter("items", items) :
                new ObjectParameter("items", typeof(decimal));
    
            var unitsParameter = units.HasValue ?
                new ObjectParameter("units", units) :
                new ObjectParameter("units", typeof(decimal));
    
            var listsParameter = lists.HasValue ?
                new ObjectParameter("lists", lists) :
                new ObjectParameter("lists", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<close_travel_Result>("close_travel", tidParameter, user_idParameter, amountParameter, amount_dParameter, cashParameter, cash_dParameter, cridetParameter, cridet_dParameter, scashParameter, dcashParameter, recridetuParameter, recridetu_dParameter, recridethParameter, recrideth_dParameter, dcashhParameter, scashhParameter, sfinalParameter, dfinalParameter, itemsParameter, unitsParameter, listsParameter);
        }
    
        public virtual ObjectResult<import_travel_data_Result> import_travel_data(Nullable<int> travel_id, Nullable<int> user_id, Nullable<System.DateTime> str_date)
        {
            var travel_idParameter = travel_id.HasValue ?
                new ObjectParameter("travel_id", travel_id) :
                new ObjectParameter("travel_id", typeof(int));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var str_dateParameter = str_date.HasValue ?
                new ObjectParameter("str_date", str_date) :
                new ObjectParameter("str_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<import_travel_data_Result>("import_travel_data", travel_idParameter, user_idParameter, str_dateParameter);
        }
    }
}
