//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALIBA_COMPANY
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ads
    {
        public int ad_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string image_url { get; set; }
        public string title { get; set; }
        public string subtitle { get; set; }
        public bool is_active { get; set; }
        public int sort_order { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string ad_type { get; set; }
    
        public virtual TB_users TB_users { get; set; }
    }
}
