//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALIBA_COMPANY
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_branchs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_branchs()
        {
            this.TB_order = new HashSet<TB_order>();
        }
    
        public int br_id { get; set; }
        public string br_name { get; set; }
        public string br_code { get; set; }
        public Nullable<bool> br_activity { get; set; }
        public string br_phone { get; set; }
        public string br_address { get; set; }
        public string br_nots { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_order> TB_order { get; set; }
    }
}
