//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALIBA_COMPANY
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_cust
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_cust()
        {
            this.TB_cridet = new HashSet<TB_cridet>();
        }
    
        public int cust_id { get; set; }
        public string cust_name { get; set; }
        public Nullable<bool> cust_activity { get; set; }
        public string cust_address { get; set; }
        public string cust_phone { get; set; }
        public Nullable<decimal> cust_min { get; set; }
        public Nullable<decimal> cust_max { get; set; }
        public string cus_nots { get; set; }
        public Nullable<int> city_id { get; set; }
    
        public virtual TB_city TB_city { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_cridet> TB_cridet { get; set; }
    }
}
