//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALIBA_COMPANY
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_cars()
        {
            this.TB_travel = new HashSet<TB_travel>();
        }
    
        public int car_id { get; set; }
        public string car_name { get; set; }
        public string car_type { get; set; }
        public Nullable<bool> car_activity { get; set; }
        public string car_inf { get; set; }
        public string car_num { get; set; }
        public Nullable<bool> car_traval_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_travel> TB_travel { get; set; }
    }
}
