//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALIBA_COMPANY
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_cridet
    {
        public int cridet_id { get; set; }
        public Nullable<System.DateTime> cridet_date { get; set; }
        public Nullable<decimal> cridet_amount { get; set; }
        public Nullable<decimal> cridet_s { get; set; }
        public Nullable<decimal> cridet_d { get; set; }
        public Nullable<decimal> cridet_ex { get; set; }
        public Nullable<int> tr_id { get; set; }
        public Nullable<int> emplo_id { get; set; }
        public Nullable<int> action_id { get; set; }
        public string cridet_nots { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> cust_id { get; set; }
        public string list_name { get; set; }
        public Nullable<int> cridet_code { get; set; }
        public Nullable<int> pr_id { get; set; }
        public Nullable<bool> sending { get; set; }
    
        public virtual TB_action TB_action { get; set; }
        public virtual TB_cust TB_cust { get; set; }
        public virtual TB_emplo TB_emplo { get; set; }
        public virtual TB_users TB_users { get; set; }
    }
}
