//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALIBA_COMPANY
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_details1
    {
        public int details_id { get; set; }
        public int order_id { get; set; }
        public Nullable<int> items_id { get; set; }
        public Nullable<int> action_id { get; set; }
        public Nullable<decimal> details_num { get; set; }
        public Nullable<decimal> details_renum { get; set; }
        public Nullable<decimal> sell_num { get; set; }
        public Nullable<bool> sending { get; set; }
    }
}
