//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALIBA_COMPANY
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_det1
    {
        public int de_id { get; set; }
        public Nullable<int> list_id { get; set; }
        public Nullable<int> items_id { get; set; }
        public Nullable<decimal> de_costUsd { get; set; }
        public Nullable<decimal> de_totalUsd { get; set; }
        public Nullable<decimal> de_num { get; set; }
        public Nullable<decimal> de_costIQ { get; set; }
        public Nullable<decimal> de_totalIQ { get; set; }
        public Nullable<bool> sending { get; set; }
    }
}
