//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALIBA_COMPANY
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_emr
    {
        public int emr_id { get; set; }
        public Nullable<System.DateTime> emr_date { get; set; }
        public Nullable<System.DateTime> emr__dateFrom { get; set; }
        public Nullable<System.DateTime> emr__dateTo { get; set; }
        public Nullable<int> emst_id { get; set; }
        public Nullable<int> emr_num { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> emplo_id { get; set; }
        public string emr_note { get; set; }
        public Nullable<int> action_id { get; set; }
    
        public virtual TB_action TB_action { get; set; }
        public virtual TB_emplo TB_emplo { get; set; }
        public virtual TB_emst TB_emst { get; set; }
        public virtual TB_users TB_users { get; set; }
    }
}
