//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALIBA_COMPANY
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_emplo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_emplo()
        {
            this.TB_cridet = new HashSet<TB_cridet>();
            this.TB_emr = new HashSet<TB_emr>();
            this.TB_list = new HashSet<TB_list>();
            this.TB_travel = new HashSet<TB_travel>();
        }
    
        public int emplo_id { get; set; }
        public string emplo_job { get; set; }
        public string emplo_pirth { get; set; }
        public string emplo_phone { get; set; }
        public Nullable<decimal> emplo_sel { get; set; }
        public Nullable<decimal> emplo_wek { get; set; }
        public string emplo_inf { get; set; }
        public Nullable<bool> emplo_activity { get; set; }
        public string emplo_name { get; set; }
        public string emplo_address { get; set; }
        public Nullable<bool> emplo_dis { get; set; }
        public string emplo_eng { get; set; }
        public Nullable<bool> emplo_traval_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_cridet> TB_cridet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_emr> TB_emr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_list> TB_list { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_travel> TB_travel { get; set; }
    }
}
