//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALIBA_COMPANY
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_items()
        {
            this.TB_det = new HashSet<TB_det>();
            this.TB_details = new HashSet<TB_details>();
            this.TB_str = new HashSet<TB_str>();
            this.TB_temp = new HashSet<TB_temp>();
        }
    
        public int items_id { get; set; }
        public string items_name { get; set; }
        public Nullable<bool> items_activity { get; set; }
        public Nullable<decimal> Usd_upper { get; set; }
        public Nullable<decimal> Usd_lower { get; set; }
        public Nullable<decimal> exchang { get; set; }
        public Nullable<decimal> IQD_upper { get; set; }
        public Nullable<decimal> IQD_lower { get; set; }
        public string items_form { get; set; }
        public Nullable<byte> items_quart { get; set; }
        public string items_nots { get; set; }
        public string items_code { get; set; }
        public string items_enname { get; set; }
        public Nullable<byte> groups_id { get; set; }
        public string items_pic { get; set; }
        public Nullable<int> items_l { get; set; }
        public Nullable<int> pr_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_det> TB_det { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_details> TB_details { get; set; }
        public virtual TB_groups TB_groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_str> TB_str { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_temp> TB_temp { get; set; }
    }
}
