//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALIBA_COMPANY
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_list
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_list()
        {
            this.TB_det = new HashSet<TB_det>();
        }
    
        public int list_id { get; set; }
        public Nullable<System.DateTime> list_date { get; set; }
        public Nullable<int> tr_id { get; set; }
        public Nullable<int> cust_idd { get; set; }
        public string list_name { get; set; }
        public Nullable<decimal> list_amountUsd { get; set; }
        public Nullable<decimal> list_amountIQ { get; set; }
        public Nullable<decimal> list_cridetUsd { get; set; }
        public Nullable<decimal> list_cridetIQ { get; set; }
        public Nullable<decimal> list_scashUsd { get; set; }
        public Nullable<decimal> list_dcash { get; set; }
        public Nullable<decimal> list_exch { get; set; }
        public Nullable<decimal> list_items { get; set; }
        public Nullable<decimal> list_unit { get; set; }
        public Nullable<int> action_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> type_id { get; set; }
        public string list_nots { get; set; }
        public Nullable<int> list_code { get; set; }
        public Nullable<int> pr_id { get; set; }
        public Nullable<bool> sending { get; set; }
        public Nullable<int> emplo_id { get; set; }
        public Nullable<int> cust_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_det> TB_det { get; set; }
        public virtual TB_emplo TB_emplo { get; set; }
        public virtual TB_travel TB_travel { get; set; }
    }
}
