//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALIBA_COMPANY
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_mov
    {
        public int mov_id { get; set; }
        public Nullable<System.DateTime> mov_date { get; set; }
        public string mov_dis { get; set; }
        public Nullable<int> amov_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual TB_amov TB_amov { get; set; }
        public virtual TB_users TB_users { get; set; }
    }
}
