//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALIBA_COMPANY
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_order
    {
        public int order_id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<decimal> order_items { get; set; }
        public Nullable<decimal> order_unit { get; set; }
        public Nullable<int> emplo_id { get; set; }
        public Nullable<int> car_id { get; set; }
        public string driver_name { get; set; }
        public string car_name { get; set; }
        public string order_nots { get; set; }
        public Nullable<int> order_code { get; set; }
        public Nullable<int> br_id { get; set; }
        public Nullable<int> action_id { get; set; }
        public string order_status { get; set; }
        public string order_ncode { get; set; }
        public Nullable<System.DateTime> order_ndate { get; set; }
    
        public virtual TB_action TB_action { get; set; }
        public virtual TB_branchs TB_branchs { get; set; }
        public virtual TB_users TB_users { get; set; }
    }
}
