//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALIBA_COMPANY
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_permissions
    {
        public int perm_id { get; set; }
        public string perm_role { get; set; }
        public string perm_key { get; set; }
        public bool perm_allowed { get; set; }
    }
}
