//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALIBA_COMPANY
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_str1
    {
        public int str_id { get; set; }
        public int order_id { get; set; }
        public int items_id { get; set; }
        public System.DateTime str_date { get; set; }
        public int action_id { get; set; }
        public Nullable<decimal> str_num { get; set; }
        public Nullable<decimal> str_renum { get; set; }
    }
}
