//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALIBA_COMPANY
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_stock
    {
        public int sto_id { get; set; }
        public Nullable<System.DateTime> sto_date { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<decimal> sto_items { get; set; }
        public Nullable<decimal> sto_unit { get; set; }
        public string sto_nots { get; set; }
    
        public virtual TB_users TB_users { get; set; }
    }
}
