//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALIBA_COMPANY
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_travel1
    {
        public Nullable<int> city_id { get; set; }
        public Nullable<int> emplo_id { get; set; }
        public Nullable<System.DateTime> tr_date { get; set; }
        public Nullable<int> car_id { get; set; }
        public Nullable<int> tr_st_id { get; set; }
        public string tr_st_staus { get; set; }
        public string tr_nots { get; set; }
        public Nullable<decimal> tr_items { get; set; }
        public Nullable<decimal> tr_unit { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> action_id { get; set; }
        public Nullable<decimal> tr_reitems { get; set; }
        public Nullable<decimal> tr_reunit { get; set; }
        public int tr_id { get; set; }
        public Nullable<decimal> tr_amount { get; set; }
        public Nullable<decimal> tr_amount_d { get; set; }
        public Nullable<decimal> tr_cash { get; set; }
        public Nullable<decimal> tr_cash_d { get; set; }
        public Nullable<decimal> tr_cridet { get; set; }
        public Nullable<decimal> tr_cridet_d { get; set; }
        public Nullable<decimal> tr_Scash { get; set; }
        public Nullable<decimal> tr_dcash { get; set; }
        public Nullable<decimal> tr_recridetu { get; set; }
        public Nullable<decimal> tr_recridetu_d { get; set; }
        public Nullable<decimal> tr_recrideth { get; set; }
        public Nullable<decimal> tr_recrideth_d { get; set; }
        public Nullable<decimal> tr_p_it { get; set; }
        public Nullable<decimal> tr_p_un { get; set; }
        public string tr_luck { get; set; }
        public Nullable<decimal> tr_dcashh { get; set; }
        public Nullable<decimal> tr_scashh { get; set; }
        public Nullable<decimal> tr_sfinal { get; set; }
        public Nullable<decimal> tr_dfinal { get; set; }
        public Nullable<int> tr_lists { get; set; }
        public Nullable<int> user_id2 { get; set; }
        public Nullable<int> tr_rate { get; set; }
        public Nullable<byte> tr_loading { get; set; }
        public Nullable<bool> tr_sending { get; set; }
    }
}
