//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALIBA_COMPANY
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_temp
    {
        public int temp_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> items_id { get; set; }
        public Nullable<int> action_id { get; set; }
        public Nullable<decimal> temp_num { get; set; }
        public Nullable<decimal> temp_renum { get; set; }
        public Nullable<System.DateTime> temp_date { get; set; }
        public int user_id { get; set; }
    
        public virtual TB_items TB_items { get; set; }
    }
}
