//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALIBA_COMPANY
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_users()
        {
            this.TB_cridet = new HashSet<TB_cridet>();
            this.TB_emr = new HashSet<TB_emr>();
            this.TB_mov = new HashSet<TB_mov>();
            this.TB_order = new HashSet<TB_order>();
            this.TB_stock = new HashSet<TB_stock>();
            this.TB_travel = new HashSet<TB_travel>();
            this.TB_travel1 = new HashSet<TB_travel>();
            this.TB_ads = new HashSet<TB_ads>();
        }
    
        public int user_id { get; set; }
        public string user_FullName { get; set; }
        public string user_name { get; set; }
        public string user_passward { get; set; }
        public string user_role { get; set; }
        public Nullable<System.DateTime> user_addDate { get; set; }
        public Nullable<int> IDDep { get; set; }
        public string DepName { get; set; }
        public Nullable<bool> user_state { get; set; }
        public bool user_activity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_cridet> TB_cridet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_emr> TB_emr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_mov> TB_mov { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_order> TB_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_stock> TB_stock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_travel> TB_travel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_travel> TB_travel1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ads> TB_ads { get; set; }
    }
}
